armor-durability-reduction-factor: 1.4 # скорость ломание брони
armor-repair-xp-factor: 4.0 # скорость починки брони за опыт (чем больше, тем быстрее)
disable-attack-cooldown: true
max-cps: 15 # абу бандит
sword-damage:
  wooden: 4.0
  stone: 5.0
  iron: 6.0
  golden: 4.0
  diamond: 7.0
  netherite: 12.5
  trident: 7.0
